### ISSUE TITLE
Allow temporal variability in the background stratification

### ISSUE THREAD

**Issue by roxyboy** [bderembl/msom#5]
I'm going to start opening issues so that we (I) can keep track of the ideas and progress on Github. I hope that's ok with you @bderembl ?

**Comment by roxyboy** [comment]
I think the main idea would be to:

- [ ] allow for the Froude number to vary with a relaxation time as we do for the passive tracer relaxation.

**Comment by bderembl** [comment]
done in PR#6

**Comment by roxyboy** [comment]
@bderembl I'm realizing that by setting the Froude number to have a sinusoid function, the background buoyancy frequency squared (N^2) will have a function of inverse sinusoid squared, leading to an asymmetry in seasonality... Do you think this is undesirable??

**Comment by bderembl** [comment]
good point.

Chelton et al (https://doi.org/10.1175/1520-0485(1998)028<0433:GVOTFB>2.0.CO;2 )
mention that the first deformation radius varies seasonally as a sum of sine and
cosine and the overall variations are O(1%) (see their fig. 12).

Let suppose Rd_1 ~ NH/f

and N = N_0 + epsilon,
with N_0 the annual mean and epsilon the seasonal variations.

then Fr = U/NH ~ (U/N_0H) - U/N_0H * epsilon/N_0

so because the variations are small, it is ok if the froude number varies as a
sine function.

one a related note: what seems to be ok for the first deformation radius is
probably not true for higher modes where epsilon may not be small. But I guess
no one has ever checked that. Having an update of Chelton's work for more modes
and for seasonal variations would actually be a valuable contribution.

**Comment by roxyboy** [comment]
Thanks for the reference, I'll check out their paper. In the mean time, I made a PR #9 so that N2 has the sinusoid form.
